version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # The root pom
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"

  # The scheduler pom
  - package-ecosystem: "maven"
    directory: "/scheduler/"
    schedule:
      interval: "weekly"

  # Gomod updates
  - package-ecosystem: "gomod"
    directory: "/src/autoscaler/"
    schedule:
      interval: "weekly"
