os: linux
dist: xenial

env:
  global:
    - NODE_VERSION=6.2
    - GO_VERSION=1.13.3
    - LOGLEVEL=info
language: java
cache:
  directories:
    - $HOME/.m2
jdk:
  - openjdk8
services:
  - postgresql
addons:
  postgresql: "9.6"
before_install:
  - source .envrc
install:
  - mvn package
  - npm install npm@latest -g
  - nvm install $NODE_VERSION --silent
  - eval "$(gimme $GO_VERSION)"
  - go install github.com/onsi/ginkgo/ginkgo

before_script:
  - nvm use $NODE_VERSION
  - psql -c 'CREATE DATABASE autoscaler' -U postgres
  - java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:postgresql://127.0.0.1/autoscaler --driver=org.postgresql.Driver --changeLogFile=api/db/api.db.changelog.yml update
  - java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:postgresql://127.0.0.1/autoscaler --driver=org.postgresql.Driver --changeLogFile=src/autoscaler/api/db/servicebroker.db.changelog.yaml update
  - java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:postgresql://127.0.0.1/autoscaler --driver=org.postgresql.Driver --changeLogFile=scheduler/db/scheduler.changelog-master.yaml update
  - java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:postgresql://127.0.0.1/autoscaler --driver=org.postgresql.Driver --changeLogFile=scheduler/db/quartz.changelog-master.yaml update
  - java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:postgresql://127.0.0.1/autoscaler --driver=org.postgresql.Driver --changeLogFile=src/autoscaler/metricscollector/db/metricscollector.db.changelog.yml update
  - java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:postgresql://127.0.0.1/autoscaler --driver=org.postgresql.Driver --changeLogFile=src/autoscaler/eventgenerator/db/dataaggregator.db.changelog.yml update
  - java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:postgresql://127.0.0.1/autoscaler --driver=org.postgresql.Driver --changeLogFile=src/autoscaler/scalingengine/db/scalingengine.db.changelog.yml update
  - java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:postgresql://127.0.0.1/autoscaler --driver=org.postgresql.Driver --changeLogFile=src/autoscaler/operator/db/operator.db.changelog.yml update
  - wget https://repo.mysql.com//mysql-apt-config_0.8.14-1_all.deb
  - sudo dpkg -i mysql-apt-config_0.8.14-1_all.deb
  - sudo apt-get update -q
  - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
  - echo -e "[mysqld]\nsql_mode=NO_ENGINE_SUBSTITUTION,STRICT_ALL_TABLES\n[server]\ninnodb_log_file_size=256MB\ninnodb_buffer_pool_size=512MB\nmax_allowed_packet=32MB" | sudo tee -a /etc/mysql/my.cnf
  - sudo systemctl restart mysql
  - sudo mysql_upgrade
  - mysql --version
  - mysql -u root -e "CREATE DATABASE autoscaler;"
  - java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:mysql://127.0.0.1/autoscaler --driver=com.mysql.cj.jdbc.Driver --changeLogFile=api/db/api.db.changelog.yml --username=root update
  - java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:mysql://127.0.0.1/autoscaler --driver=com.mysql.cj.jdbc.Driver --changeLogFile=src/autoscaler/api/db/servicebroker.db.changelog.yaml --username=root update
  - java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:mysql://127.0.0.1/autoscaler --driver=com.mysql.cj.jdbc.Driver --changeLogFile=scheduler/db/scheduler.changelog-master.yaml --username=root update
  - java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:mysql://127.0.0.1/autoscaler --driver=com.mysql.cj.jdbc.Driver --changeLogFile=scheduler/db/quartz.changelog-master.yaml --username=root update

  - java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:mysql://127.0.0.1/autoscaler --driver=com.mysql.cj.jdbc.Driver --changeLogFile=src/autoscaler/metricscollector/db/metricscollector.db.changelog.yml --username=root update
  - java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:mysql://127.0.0.1/autoscaler --driver=com.mysql.cj.jdbc.Driver --changeLogFile=src/autoscaler/eventgenerator/db/dataaggregator.db.changelog.yml --username=root update
  - java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:mysql://127.0.0.1/autoscaler --driver=com.mysql.cj.jdbc.Driver --changeLogFile=src/autoscaler/scalingengine/db/scalingengine.db.changelog.yml --username=root update
  - java -cp 'db/target/lib/*' liquibase.integration.commandline.Main --url jdbc:mysql://127.0.0.1/autoscaler --driver=com.mysql.cj.jdbc.Driver --changeLogFile=src/autoscaler/operator/db/operator.db.changelog.yml --username=root update
jobs:
  include:
    - name: unit test
      script:
        # Unit test
        - pushd src/autoscaler
        - sudo cp /var/lib/mysql/ca.pem /tmp/ca.pem
        - export DBURL="postgres://postgres@localhost/autoscaler?sslmode=disable"
        - ginkgo -r -race -randomizeAllSpecs
        - export DBURL="root@tcp(localhost)/autoscaler?tls=false"
        - ginkgo -r -race -randomizeAllSpecs
        - popd
        - sudo rm /tmp/ca.pem
        - pushd scheduler
        - mvn test
        - mvn test -Dspring.profiles.active=mysql

    - name: integration test
      script:
        # Integration test
        - pushd scheduler
        - mvn package -DskipTests
        - popd
        - export DBURL="postgres://postgres@localhost/autoscaler?sslmode=disable"
        - ginkgo -r -race -randomizeAllSpecs src/integration
        - export DBURL="root@tcp(localhost)/autoscaler?tls=false"
        - ginkgo -r -race -randomizeAllSpecs src/integration
    # Tests for legacy components (node apiserver, broker and metricscollector)
    # - name: legacy unit test
    #   script:
    #     - pushd api
    #     - npm install
    #     - npm test
    #     - popd
    #     - pushd servicebroker
    #     - npm install
    #     - npm test
    #     - popd

    # - name: legacy integration test
    #   script:
    #     - pushd api
    #     - npm install
    #     - npm test
    #     - popd
    #     - pushd servicebroker
    #     - npm install
    #     - npm test
    #     - popd
    #     - pushd scheduler
    #     - mvn package -DskipTests
    #     - popd
    #     - ginkgo -r -race -randomizeAllSpecs src/integration_legacy

