name: Linters

on:
  pull_request:
  workflow_dispatch:

jobs:
  linters:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Trust my checkout
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"
      - name: Install devbox
        uses: jetify-com/devbox-install-action@a0d2d53632934ae004f878c840055956d9f741b0 # v0.14.0
        with:
          enable-cache: 'true'
      - name: Make devbox shellenv available
        run: |
          eval "$(devbox shellenv)"
          printenv >> "$GITHUB_ENV"

      - name: Run Go linter
        run: |
          make lint-go
      - name: shellcheck
        uses: reviewdog/action-shellcheck@4c07458293ac342d477251099501a718ae5ef86e # v1
        with:
          reporter: github-pr-check
          fail_level: error
      - name: actionlint
        uses: reviewdog/action-actionlint@0d952c597ef8459f634d7145b0b044a9699e5e43 # v1
        with:
          reporter: github-pr-review
      - name: Create alex config
        run: |
          cat > .alexrc << 'EOF'
          {
            "allow": [
              "execute",
              "executes",
              "executed",
              "executing",
              "execution",
              "period",
              "periods",
              "trap",
              "traps",
              "trapped",
              "trapping"
            ]
          }
          EOF
      - name: alex
        uses: reviewdog/action-alex@6083b8ca333981fa617c6828c5d8fb21b13d916b # v1
        with:
          reporter: github-pr-review
      - name: markdownlint
        uses: reviewdog/action-markdownlint@3667398db9118d7e78f7a63d10e26ce454ba5f58 # v0
        with:
          reporter: github-pr-review
