name: Suspend CI VMs

on:
  schedule:
    - cron: '0 17 * * 1-5'  # 17:00 UTC / 18:00 CET / 19:00 CEST, Monday to Friday
  workflow_dispatch:

jobs:
  suspend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: auth gcloud
        uses: google-github-actions/auth@c200f3691d83b41bf9bbd8638997a462592937ed # v2
        with:
          credentials_json: '${{ secrets.GCP_APP_RUNTIME_INTERFACES_AUTOSCALER_DEPLOYER_KEY }}'

      - name: set up gcloud
        uses: google-github-actions/setup-gcloud@e427ad8a34f8676edf47cf7d7925499adf3eb74f # v2

      - name: suspend VMs
        run: |
          gcloud compute instances list --filter="networkInterfaces.network:autoscaler-network" --format="value(name,zone)" --sort-by="labels.deployment:bosh" | while read -r INSTANCE_NAME ZONE; do
            if ! gcloud compute instances suspend "$INSTANCE_NAME" --zone="$ZONE" --async; then
              echo "failed to initiate suspending $INSTANCE_NAME in $ZONE, continuing with next instance"
              continue
            fi
          done
