name: Suspend CI VMs

on:
  schedule:
    - cron: '0 17 * * 1-5'  # 17:00 UTC / 18:00 CET / 19:00 CEST, Monday to Friday
  workflow_dispatch:

jobs:
  suspend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: auth gcloud
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3
        with:
          credentials_json: '${{ secrets.GCP_APP_RUNTIME_INTERFACES_AUTOSCALER_DEPLOYER_KEY }}'

      - name: set up gcloud
        uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3

      - name: suspend VMs
        run: |
          gcloud compute instances list --filter="networkInterfaces.network:autoscaler-network" --format="value(name,zone)" --sort-by="labels.deployment:bosh" | while read -r INSTANCE_NAME ZONE; do
            if ! gcloud compute instances suspend "$INSTANCE_NAME" --zone="$ZONE" --async; then
              echo "failed to initiate suspending $INSTANCE_NAME in $ZONE, continuing with next instance"
              continue
            fi
          done
